-- =========================================================
-- AL-TOQA FURNITURE / SUPABASE SETUP
-- Run this in Supabase SQL Editor.
-- If you already have a products table, compare the columns
-- before running ALTER statements.
-- =========================================================

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  "categoryName" text,
  code text unique,
  description text,
  material text,
  dimensions text,
  colors jsonb not null default '[]'::jsonb,
  image text,
  images jsonb not null default '[]'::jsonb,
  featured boolean not null default false,
  status text NOT NULL DEFAULT 'active',
  active boolean not null default true,
  "subcategoryId" text,
  "subcategoryName" text,
  "subCategoryId" text,
  "subCategoryName" text,
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz
);

-- If your existing products table is missing any of the fields above,
-- add the missing fields manually with the appropriate ALTER TABLE.

create index if not exists products_active_idx on public.products(active);
create index if not exists products_category_idx on public.products(category);
create index if not exists products_featured_idx on public.products(featured);

-- Public read is intentionally NOT enabled here.
-- The Flask API reads with the server-side Supabase key.
-- Do not put a service-role key in browser JavaScript.

-- ---------------------------------------------------------
-- Storage bucket for product images
-- ---------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

-- Public read of product images.
drop policy if exists "Public can read product images" on storage.objects;
create policy "Public can read product images"
on storage.objects for select
to public
using (bucket_id = 'product-images');

-- Upload/update/delete is performed by Flask with the server key.
-- Do NOT expose the server key in frontend code.


-- ---------------------------------------------------------
-- Categories / Banners / Quotes: all persistent content lives in Supabase.
-- Flask uses the server key; browser never receives it.
-- ---------------------------------------------------------
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  "parentCategory" text not null,
  image text,
  active boolean not null default true,
  "createdAt" timestamptz not null default now()
);
create index if not exists categories_active_idx on public.categories(active);

create table if not exists public.banners (
  id bigint generated by default as identity primary key,
  title text not null,
  text text,
  button text,
  link text,
  image text not null,
  active boolean not null default true,
  "sortOrder" integer not null default 0,
  "createdAt" timestamptz not null default now()
);
create index if not exists banners_active_idx on public.banners(active);

create table if not exists public.quotes (
  id text primary key,
  "customerName" text not null,
  "companyName" text not null,
  "customerPhone" text not null,
  "customerEmail" text,
  "projectType" text,
  "quoteDetails" text,
  budget text,
  "deliveryDate" text,
  "contactMethod" text,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric not null default 0,
  "vatRate" numeric not null default 0,
  "vatAmount" numeric not null default 0,
  "grandTotal" numeric not null default 0,
  "paymentTerms" text,
  "deliveryPeriod" text,
  warranty text,
  status text not null default 'new',
  "createdAt" timestamptz not null default now(),
  "updatedAt" timestamptz
);
create index if not exists quotes_created_idx on public.quotes("createdAt" desc);

-- For existing databases created before the warranty field was added.
alter table public.quotes add column if not exists warranty text;

insert into storage.buckets (id, name, public)
values ('site-images', 'site-images', true)
on conflict (id) do update set public = true;
drop policy if exists "Public can read site images" on storage.objects;
create policy "Public can read site images" on storage.objects for select to public using (bucket_id = 'site-images');

-- Lock database tables from direct browser access. The Flask server uses the server key.
alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.banners enable row level security;
alter table public.quotes enable row level security;
